development:
  adapter: postgresql
  encoding: utf8
  database: db/development
  host: localhost
  pool: 5
  timeout: 5000
  username: sfinley
  password: password

test:
  adapter: postgresql
  encoding: utf8
  database: db/test
  pool: 5
  timeout: 5000
  username: sfinley
  password: password

production:
  adapter: postgresql
  encoding: utf8
  database: db/production
  pool: 5
  timeout: 5000
  username: sfinley
  password: password